services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Softspring\CmsBundle\Manager\ContentEntityDuplicatorInterface:
            tags: [ 'sfs_cms.content_entity_duplicator' ]

    Softspring\CmsBlogPlugin\Controller\:
        resource: '../../src/Controller/*'
        tags: ['controller.service_arguments']

    Softspring\CmsBlogPlugin\Form\:
        resource: '../../src/Form/*'
        tags: ['form.type']

    Softspring\CmsBlogPlugin\Data\:
        resource: '../../src/Data/*'

    Softspring\CmsBlogPlugin\Manager\:
        resource: '../../src/Manager/*'

    Softspring\CmsBlogPlugin\EventListener\OverrideDoctrineClassSuperclassListener:
        arguments:
            $superclassList: '%sfs_cms_blog.convert_superclass_list%'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, priority: 500 }