services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CmsBlogBundle\Controller\:
        resource: '../../src/Controller/*'
        tags: ['controller.service_arguments']

    Softspring\CmsBlogBundle\Form\:
        resource: '../../src/Form/*'
        tags: ['form.type']

    Softspring\CmsBlogBundle\Data\:
        resource: '../../src/Data/*'
