_sfs_cms_blog_articles_:
    resource: "@SfsCmsBundle/config/routing/admin_content_type.yaml"
    prefix: "/articles"
    defaults:
        _content_type: article
    name_prefix: sfs_cms_admin_content_article_
