cms_blog_block_article_list:
    path: /_blog_blocks/article-list
    controller: Softspring\CmsBlogBundle\Controller\ArticleController::listBlock

cms_blog_block_article_header_data:
    path: /_blog_blocks/{article}/article-header-data
    controller: Softspring\CmsBlogBundle\Controller\ArticleController::headerDataBlock