content:
    revision: 1
    entity_class: 'Softspring\CmsBlogPlugin\Entity\ArticleContent'

    admin:
#        list_view: '@content/article/admin/list.html.twig'
        list_page_view: '@content/article/admin/list-page.html.twig'
        create_type: 'Softspring\CmsBlogPlugin\Form\Admin\Article\ArticleCreateForm'
        update_type: 'Softspring\CmsBlogPlugin\Form\Admin\Article\ArticleUpdateForm'
##    #    content_form_type: 'App\Form\Admin\Cms\CertificateContentForm'
        create_view: '@content/article/admin/create.html.twig'
        update_view: '@content/article/admin/update.html.twig'

    default_layout: 'article'

#    # layout: 'default' # ?
#
#    containers: ~

    extra_fields:
        title:
            type: 'translatable'
        description:
            type: 'translatable'
            type_options:
                type: 'textarea'


