content:
    revision: 1
    entity_class: 'Softspring\CmsBlogPlugin\Entity\ArticleContent'

    admin:
        list:
            view: '@content/article/admin/list.html.twig'
            page_view: '@content/article/admin/list-page.html.twig'
            filter_form: 'Softspring\CmsBlogPlugin\Form\Admin\Article\ArticleListFilterForm'
        create:
            type: 'Softspring\CmsBlogPlugin\Form\Admin\Article\ArticleCreateForm'
            view: '@content/article/admin/create.html.twig'
        update:
            type: 'Softspring\CmsBlogPlugin\Form\Admin\Article\ArticleUpdateForm'
            view: '@content/article/admin/update.html.twig'

    default_layout: 'article'

#    # layout: 'default' # ?
#
#    containers: ~

    extra_fields:
        title:
            type: 'translatable'
        description:
            type: 'translatable'
            type_options:
                type: 'textarea'


