module:
    group: blog
    revision: 2
    edit_template: '@module/article_link_list/edit.html.twig'
    form_template: '@module/article_link_list/form.html.twig'
    render_template: '@module/article_link_list/render.html.twig'
    module_options:
        form_fields:
            id:
                type: 'id'

            class:
                type: 'class'

            title:
                type: 'translation'
                type_options:
                    required: false
                    children_attr:
                        data-article-list-preview-param: 'title'

            tag:
                type: 'Softspring\CmsBlogPlugin\Form\Type\BlogArticleTagType'
                type_options:
                    required: false
                    placeholder: 'article_link_list.form.tag.placeholder'
                    attr:
                        data-article-list-preview-param: 'tag'

            limit:
                type: 'integer'
                type_options:
                    required: false
                    empty_data: 5
                    default_value: 5
                    attr:
                        min: 1
                        data-article-list-preview-param: 'limit'

            order:
                type: 'choice'
                type_options:
                    required: false
                    default_value: 'published_at_desc'
                    attr:
                        data-article-list-preview-param: 'article_order'
                    choices:
                        'article_link_list.form.order.values.published_at_desc': 'published_at_desc'
                        'article_link_list.form.order.values.published_at_asc': 'published_at_asc'
                        'article_link_list.form.order.values.name_asc': 'name_asc'
                        'article_link_list.form.order.values.name_desc': 'name_desc'
